### ISSUE TITLE
Create new logo for Pyrrha

### ISSUE THREAD

**Issue by krook** [Pyrrha-Platform/Pyrrha#20]
This is the design prompt and background:

[Pyrrha was the daughter-in-law of Prometheus](https://www.greekmythology.com/Myths/Mortals/Pyrrha/pyrrha.html). [Additional background](https://en.wikipedia.org/wiki/Pyrrha_of_Thessaly).

> "In Latin the word pyrrhus means red from the Greek adjective πυρρός, purrhos, i.e. "flame coloured", "the colour of fire", "fiery red" or simply "red" or "reddish". Pyrrha was evidently named after her red hair as Horace and Ovid describe her as red haired."

**Comment by Aquijada52** [comment]
Reached out in intern design slack, will update if anyone reaches out or shows interest

**Comment by krook** [comment]
Did you ever hear back @Aquijada52?

**Comment by Aquijada52** [comment]
Nope, but i can try to bring it up tomorrow again in the slack

**Comment by Aquijada52** [comment]
![logo](https://user-images.githubusercontent.com/84873806/122596379-9ad24580-d01e-11eb-82db-83d1c14c7829.jpeg)
thoughts? colors n logos can be easily changed

**Comment by krook** [comment]
We've created a version for launch. So for now I'll close this. We can revisit in the future. I appreciate the effort @Aquijada52!
