### ISSUE TITLE
Replace github img links with local relative links

### ISSUE THREAD

**Issue by upkarlidder** [Pyrrha-Platform/Pyrrha#39]
@TaeBlack the images you put in are uploaded to github. Let's change them all to relative links. This makes it easier for us to change later.

For example:
```5. Ensure that the `Summary` page looks good, then click `Finish`.
   <img width="1920" alt="step9" src="https://user-images.githubusercontent.com/84807697/125337417-f9889780-e31c-11eb-8376-e98671f693e2.png">```

will change to 

```
5. Ensure that the `Summary` page looks good, then click `Finish`.
   <img width="1920" alt="step9" src="img/click-finish.png">
```

or 
```
5. Ensure that the `Summary` page looks good, then click `Finish`.
   ![](img/click-finish.png)
```

You will have to first copy the github image to `img/click-finish.png` image.

**Comment by TaeBlack** [comment]
finished uploading and replacing the image links
