### ISSUE TITLE
Update the main architecture diagram in Prometeo repo

### ISSUE THREAD

**Issue by upkarlidder** [Pyrrha-Platform/Pyrrha#5]
https://github.com/Pyrrha-Platform/Pyrrha

**Comment by upkarlidder** [comment]
Replace Prometeo architecture diagram in the main readme with this one:

![image](https://user-images.githubusercontent.com/3187457/120346296-19558600-c2b0-11eb-8472-894f5e8877f7.png)

**Comment by Aquijada52** [comment]
https://github.com/Call-for-Code/Pyrrha-Platform/Pyrrha 

Should take me where the Pyrrha main page should be to update the diagram, does not work as of right now.

**Comment by upkarlidder** [comment]
This is the URL: https://github.com/Pyrrha-Platform/Pyrrha

**Comment by upkarlidder** [comment]
Updated architecture diagram with numbers and steps:

-----------------

![image](https://user-images.githubusercontent.com/3187457/122242264-08903d00-ce78-11eb-944f-804ba4dc683d.png)

1. The firefighter logs into the mobile phone. The credentials are authenticated with IBM App ID. The next steps assume that authentication was successful. 
2. The device sensor captures gas levels. The mobile application polls the device for sensor values at regular intervals.
3. The mobile application sends data to the IBM IoT platform.
4. The MQTT Client service listens for incoming messages on the IBM IoT platform.
5. The MQTT Client stores the data in the MariaDB relational database.
6. The MQTT client sends the data to the WebSocket server.
7. The RulesDecision service wakes up every minute to calculate the 10 mins, 30 mins, 60 mins, 4 hours, and 8 hours time weighted averages for each gas.
8. The dashboard queries the database to show the historical data.
9. The dashboard connects to the Websocker Server to show live data and alerts the user if the levels go above certain pre-determined thresholds. 
10. The central control can view the dashboard using the web browser.
11. The mobile application regularly requests firefighter status from the RulesDecision service and shows the result using the LED on the hardware device.
-----------------

@mrodrise @JSegrave-IBM @krook : can you please confirm the flow.

FYI @Aquijada52

**Comment by mrodrise** [comment]
Hello!, good work, some small changes:

1. The firefighter logs into the mobile phone. The credentials are authenticated with IBM App ID. The next steps assume that authentication was successful. Then the firefighter scan for Prometeo devices with the mobile app and connect to the device thought bluetooth low energy.
2. The device sensor captures gas levels. The device sends to the mobile application sensor values at regular intervals.

**Comment by upkarlidder** [comment]
Thank you @mrodrise. Added your changes to my comment. 

@Aquijada52 @TaeBlack please use this version on the site as discussed.

**Comment by Aquijada52** [comment]
Just updated the diagram as well as the changes from marco
