### ISSUE TITLE
Rename repositories and documentation from Prometeo to Pyrrha

### ISSUE THREAD

**Issue by krook** [Pyrrha-Platform/Pyrrha#8]
- [x] Swap Prometeo and Pyrrha organizations
- [x] Update repo names
- [x] Update text in repos

**Comment by upkarlidder** [comment]
Daniel, creating a separate issue to `update text in repos`. Good first issue for @TaeBlack and @Aquijada52?

**Comment by krook** [comment]
Looks like this is well in hand.
